import './pages/index.css';
import teq1 from './images/cards-attention.png';
import teq2 from './images/cards-recall.png';
import teq3 from './images/cards-interliving.png';
import teq4 from './images/cards-question.png';
import teq5 from './images/cards-competence.png';
import khanBook from './images/khan-book.jpg';
import arzamas from './images/resources-arzamas.svg';
import n1 from './images/resources-n1.svg';
import strelka from './images/resources-strelka.svg';
import polka from './images/resources-polka.svg';
import facebook from './images/facebook_color_white.svg';
import vk from './images/vk_color_white.svg';
import instagram from './images/instagram_color_white.svg';

document.querySelector('#teq1').setAttribute('src', teq1);
document.querySelector('#teq2').setAttribute('src', teq2);
document.querySelector('#teq3').setAttribute('src', teq3);
document.querySelector('#teq4').setAttribute('src', teq4);
document.querySelector('#teq5').setAttribute('src', teq5);
document.querySelector('#khan').setAttribute('src', khanBook);
document.querySelector('#arzamas').setAttribute('src', arzamas);
document.querySelector('#n1').setAttribute('src', n1);
document.querySelector('#strelka').setAttribute('src', strelka);
document.querySelector('#polka').setAttribute('src', polka);
document.querySelector('#facebook').setAttribute('src', facebook);
document.querySelector('#vk').setAttribute('src', vk);
document.querySelector('#instagram').setAttribute('src', instagram);
