import './pages/index.css';
import headerLogo from './images/header-logo.svg';
import leadPolka from './images/lead__polka.jpg';
import pic1 from './images/photo-grid-train.jpg';
import pic2 from './images/photo-grid-atharva-tulsi.jpg';
import pic3 from './images/photo-grid-tuman.jpg';
import pic4 from './images/photo-grid-sochi.jpg';
import pic5 from './images/photo-grid-baikal.jpg';
import pic6 from './images/photo-grid-elbrus.jpg';
import pic7 from './images/photo-grid-kondratiev.jpg';
import pic8 from './images/photo-grid-kamchatka-1.jpg';
import pic9 from './images/photo-grid-kamchatka-2.jpg';
import pic10 from './images/photo-grid-baikal-2.jpg';
import pic11 from './images/photo-grid-ergaki.jpg';
import pic12 from './images/photo-grid-arisa.jpg';
import place1 from './images/place-kosa.jpg';
import place2 from './images/place-kolsky.jpg';
import place3 from './images/place-altai.jpg';
import place4 from './images/place-winter-baikal.jpg';
import place5 from './images/place-karelia.jpg';

document.querySelector('#headerLogo').setAttribute('src', headerLogo);
document.querySelector('#polka').setAttribute('src', leadPolka);
document.querySelector('#pic1').setAttribute('src', pic1);
document.querySelector('#pic2').setAttribute('src', pic2);
document.querySelector('#pic3').setAttribute('src', pic3);
document.querySelector('#pic4').setAttribute('src', pic4);
document.querySelector('#pic5').setAttribute('src', pic5);
document.querySelector('#pic6').setAttribute('src', pic6);
document.querySelector('#pic7').setAttribute('src', pic7);
document.querySelector('#pic8').setAttribute('src', pic8);
document.querySelector('#pic9').setAttribute('src', pic9);
document.querySelector('#pic10').setAttribute('src', pic10);
document.querySelector('#pic11').setAttribute('src', pic11);
document.querySelector('#pic12').setAttribute('src', pic12);

document.querySelector('#place1').setAttribute('src', place1);
document.querySelector('#place2').setAttribute('src', place2);
document.querySelector('#place3').setAttribute('src', place3);
document.querySelector('#place4').setAttribute('src', place4);
document.querySelector('#place5').setAttribute('src', place5);
